#Config for PVM Plugin by taemery0
helmet: 7
chestplate: 7
leggings: 7
boots: 7
timer: 15
lobby:
  x: 0
  y: 100
  z: 50
  w: world
arenas:
  1:
    x: 0
    y: 100
    z: 0
    w: world
    active: false
  2:
    x: 0
    y: 100
    z: 0
    w: world
    active: false    